-- MySQL Script generated by MySQL Workbench
-- Sun May 24 01:43:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FlightFinder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `COUNTRIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COUNTRIES` ;

CREATE TABLE IF NOT EXISTS `COUNTRIES` (
  `country_code` VARCHAR(2) NOT NULL,
  `iso3` VARCHAR(3) NULL DEFAULT NULL,
  `name` VARCHAR(52) NULL DEFAULT NULL,
  `nationality` VARCHAR(39) NULL DEFAULT NULL,
  PRIMARY KEY (`country_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `iso3_UNIQUE` ON `COUNTRIES` (`iso3` ASC);


-- -----------------------------------------------------
-- Table `PASSENGER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PASSENGER` ;

CREATE TABLE IF NOT EXISTS `PASSENGER` (
  `passenger_id` VARCHAR(10) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `date_of_birth` DATE NULL,
  `gender` VARCHAR(6) NULL,
  `id_type` VARCHAR(10) NULL,
  `id_expiration_date` DATE NULL,
  `nationality` VARCHAR(2) NULL,
  PRIMARY KEY (`passenger_id`),
  CONSTRAINT `fk_PASSENGER_COUNTRIES1`
    FOREIGN KEY (`nationality`)
    REFERENCES `COUNTRIES` (`country_code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_PASSENGER_COUNTRIES1_idx` ON `PASSENGER` (`nationality` ASC);


-- -----------------------------------------------------
-- Table `CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(500) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `mobile` VARCHAR(10) NULL,
  `gender` VARCHAR(6) NULL,
  `joined_date` DATE NULL,
  `status` VARCHAR(50) NULL,
  `customer_type` VARCHAR(10) NULL,
  `address_line_1` VARCHAR(255) NULL,
  `address_line_2` VARCHAR(255) NULL,
  `city` VARCHAR(60) NULL,
  `country` VARCHAR(2) NULL,
  `region` VARCHAR(60) NULL,
  `postal_code` VARCHAR(8) NULL,
  `email_token` VARCHAR(100) NULL,
  `email_token_expire` DATETIME NULL,
  `password_token` VARCHAR(100) NULL,
  `password_token_expire` DATETIME NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_CUSTOMER_COUNTRIES1`
    FOREIGN KEY (`country`)
    REFERENCES `COUNTRIES` (`country_code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `CUSTOMER` (`email` ASC);

CREATE UNIQUE INDEX `email_token_UNIQUE` ON `CUSTOMER` (`email_token` ASC);

CREATE UNIQUE INDEX `password_token_UNIQUE` ON `CUSTOMER` (`password_token` ASC);

CREATE INDEX `fk_CUSTOMER_COUNTRIES1_idx` ON `CUSTOMER` (`country` ASC);


-- -----------------------------------------------------
-- Table `AIRLINE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AIRLINE` ;

CREATE TABLE IF NOT EXISTS `AIRLINE` (
  `airline_code` VARCHAR(2) NOT NULL,
  `airline_name` VARCHAR(50) NULL,
  PRIMARY KEY (`airline_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AIRPLANE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AIRPLANE` ;

CREATE TABLE IF NOT EXISTS `AIRPLANE` (
  `airplane_model` VARCHAR(3) NOT NULL,
  `airplane_name` VARCHAR(100) NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`airplane_model`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AIRPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AIRPORT` ;

CREATE TABLE IF NOT EXISTS `AIRPORT` (
  `airport_code` VARCHAR(3) NOT NULL,
  `airport_name` VARCHAR(50) NULL,
  `city` VARCHAR(50) NULL,
  `country` VARCHAR(50) NULL,
  PRIMARY KEY (`airport_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FLIGHT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FLIGHT` ;

CREATE TABLE IF NOT EXISTS `FLIGHT` (
  `flight_id` VARCHAR(10) NOT NULL,
  `airline` VARCHAR(2) NOT NULL,
  `airplane` VARCHAR(3) NOT NULL,
  `from_airport` VARCHAR(3) NOT NULL,
  `to_airport` VARCHAR(3) NOT NULL,
  `dep_date` DATE NOT NULL,
  `dep_time` TIME NULL,
  `arr_date` DATE NULL,
  `arr_time` TIME NULL,
  `duration` TIME NULL,
  `class` VARCHAR(50) NOT NULL,
  `price` INT NULL,
  `change_fee` INT NULL,
  `cancel_fee` INT NULL,
  `taxes` INT NULL,
  `discount` DECIMAL(5) NULL,
  `occupied_capacity` INT NULL,
  `status` VARCHAR(50) NULL,
  `stops` INT NULL DEFAULT 0,
  PRIMARY KEY (`flight_id`, `dep_date`, `class`),
  CONSTRAINT `fk_FLIGHT_AIRLINE1`
    FOREIGN KEY (`airline`)
    REFERENCES `AIRLINE` (`airline_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FLIGHT_AIRPLANE1`
    FOREIGN KEY (`airplane`)
    REFERENCES `AIRPLANE` (`airplane_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FLIGHT_AIRPORT1`
    FOREIGN KEY (`from_airport`)
    REFERENCES `AIRPORT` (`airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FLIGHT_AIRPORT2`
    FOREIGN KEY (`to_airport`)
    REFERENCES `AIRPORT` (`airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FLIGHT_AIRLINE1_idx` ON `FLIGHT` (`airline` ASC);

CREATE INDEX `fk_FLIGHT_AIRPLANE1_idx` ON `FLIGHT` (`airplane` ASC);

CREATE INDEX `fk_FLIGHT_AIRPORT1_idx` ON `FLIGHT` (`from_airport` ASC);

CREATE INDEX `fk_FLIGHT_AIRPORT2_idx` ON `FLIGHT` (`to_airport` ASC);


-- -----------------------------------------------------
-- Table `BOOKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BOOKING` ;

CREATE TABLE IF NOT EXISTS `BOOKING` (
  `booking_id` VARCHAR(6) NOT NULL,
  `customer_id` INT NOT NULL,
  `depart_flight_id` VARCHAR(10) NOT NULL,
  `return_flight_id` VARCHAR(10) NULL,
  `depart_flight_date` DATE NOT NULL,
  `return_flight_date` DATE NULL,
  `flight_class` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `mobile` VARCHAR(10) NULL,
  `booking_date` DATE NULL,
  `last_modify_date` DATE NULL,
  `total_passengers` INT NULL,
  `total_baggage` INT NULL,
  `baggage_per_passenger` INT NULL,
  `price_per_passenger` INT NULL,
  `total_price` INT NULL,
  `payment_type` VARCHAR(15) NULL,
  `flight_type` VARCHAR(50) NULL,
  `status` VARCHAR(50) NULL,
  PRIMARY KEY (`booking_id`, `customer_id`, `depart_flight_id`, `depart_flight_date`, `flight_class`),
  CONSTRAINT `fk_BOOKING_CUSTOMER1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `CUSTOMER` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_BOOKING_FLIGHT1`
    FOREIGN KEY (`depart_flight_id` , `depart_flight_date` , `flight_class`)
    REFERENCES `FLIGHT` (`flight_id` , `dep_date` , `class`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_BOOKING_CUSTOMER1_idx` ON `BOOKING` (`customer_id` ASC);

CREATE INDEX `fk_BOOKING_FLIGHT1_idx` ON `BOOKING` (`depart_flight_id` ASC, `depart_flight_date` ASC, `flight_class` ASC);


-- -----------------------------------------------------
-- Table `INSURANCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INSURANCE` ;

CREATE TABLE IF NOT EXISTS `INSURANCE` (
  `insurance_id` VARCHAR(6) NOT NULL,
  `medical_bills` TINYINT NULL,
  `trip_cancellation` TINYINT NULL,
  `lost_baggage` TINYINT NULL,
  `travel_insurance` TINYINT NULL,
  `liability` TINYINT NULL,
  `price` INT NULL,
  PRIMARY KEY (`insurance_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAGGAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAGGAGE` ;

CREATE TABLE IF NOT EXISTS `BAGGAGE` (
  `bag_id` VARCHAR(6) NOT NULL,
  `weight` INT NULL,
  `price` INT NULL,
  PRIMARY KEY (`bag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HAS_BOOKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HAS_BOOKING` ;

CREATE TABLE IF NOT EXISTS `HAS_BOOKING` (
  `booking_id` VARCHAR(6) NOT NULL,
  `passenger_id` VARCHAR(10) NOT NULL,
  `insurance` VARCHAR(6) NULL,
  `chkd_cabin_bag_dep` VARCHAR(6) NULL DEFAULT 'cabin',
  `chkd_cabin_bag_dep_amount` INT NULL DEFAULT 1,
  `chkd_small_bag_dep` VARCHAR(6) NULL DEFAULT 'small',
  `chkd_small_bag_dep_amount` INT NULL DEFAULT 0,
  `chkd_large_bag_dep` VARCHAR(6) NULL DEFAULT 'large',
  `chkd_large_bag_dep_amount` INT NULL DEFAULT 0,
  `chkd_cabin_bag_ret` VARCHAR(6) NULL DEFAULT 'cabin',
  `chkd_cabin_bag_ret_amount` INT NULL DEFAULT 0,
  `chkd_small_bag_ret` VARCHAR(6) NULL DEFAULT 'small',
  `chkd_small_bag_ret_amount` INT NULL DEFAULT 0,
  `chkd_large_bag_ret` VARCHAR(6) NULL DEFAULT 'large',
  `chkd_large_bag_ret_amount` INT NULL DEFAULT 0,
  PRIMARY KEY (`booking_id`, `passenger_id`),
  CONSTRAINT `fk_HAS_BOOKING_PASSENGER`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `PASSENGER` (`passenger_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BOOKING`
    FOREIGN KEY (`booking_id`)
    REFERENCES `BOOKING` (`booking_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_INSURANCE`
    FOREIGN KEY (`insurance`)
    REFERENCES `INSURANCE` (`insurance_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE1`
    FOREIGN KEY (`chkd_cabin_bag_dep`)
    REFERENCES `BAGGAGE` (`bag_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE2`
    FOREIGN KEY (`chkd_small_bag_dep`)
    REFERENCES `BAGGAGE` (`bag_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE3`
    FOREIGN KEY (`chkd_large_bag_dep`)
    REFERENCES `BAGGAGE` (`bag_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE4`
    FOREIGN KEY (`chkd_cabin_bag_ret`)
    REFERENCES `BAGGAGE` (`bag_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE5`
    FOREIGN KEY (`chkd_small_bag_ret`)
    REFERENCES `BAGGAGE` (`bag_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE6`
    FOREIGN KEY (`chkd_large_bag_ret`)
    REFERENCES `BAGGAGE` (`bag_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_HAS_BOOKING_BOOKING1_idx` ON `HAS_BOOKING` (`booking_id` ASC);

CREATE INDEX `fk_HAS_BOOKING_INSURANCE1_idx` ON `HAS_BOOKING` (`insurance` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE1_idx` ON `HAS_BOOKING` (`chkd_cabin_bag_dep` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE2_idx` ON `HAS_BOOKING` (`chkd_small_bag_dep` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE3_idx` ON `HAS_BOOKING` (`chkd_large_bag_dep` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE4_idx` ON `HAS_BOOKING` (`chkd_cabin_bag_ret` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE5_idx` ON `HAS_BOOKING` (`chkd_small_bag_ret` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE6_idx` ON `HAS_BOOKING` (`chkd_large_bag_ret` ASC);

CREATE INDEX `fk_HAS_BOOKING_PASSENGER1_idx` ON `HAS_BOOKING` (`passenger_id` ASC);


-- -----------------------------------------------------
-- Table `NEWSLETTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NEWSLETTER` ;

CREATE TABLE IF NOT EXISTS `NEWSLETTER` (
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `token` VARCHAR(100) NULL,
  `token_expire` DATETIME NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `token_UNIQUE` ON `NEWSLETTER` (`token` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `COUNTRIES`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AF', 'AFG', 'Afghanistan', 'Afghan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AX', 'ALA', 'Åland Islands', 'Åland Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AL', 'ALB', 'Albania', 'Albanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('DZ', 'DZA', 'Algeria', 'Algerian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AS', 'ASM', 'American Samoa', 'American Samoan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AD', 'AND', 'Andorra', 'Andorran');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AO', 'AGO', 'Angola', 'Angolan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AI', 'AIA', 'Anguilla', 'Anguillan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AQ', 'ATA', 'Antarctica', 'Antarctic');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AG', 'ATG', 'Antigua and Barbuda', 'Antiguan or Barbudan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AR', 'ARG', 'Argentina', 'Argentine');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AM', 'ARM', 'Armenia', 'Armenian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AW', 'ABW', 'Aruba', 'Aruban');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AU', 'AUS', 'Australia', 'Australian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AT', 'AUT', 'Austria', 'Austrian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AZ', 'AZE', 'Azerbaijan', 'Azerbaijani, Azeri');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BS', 'BHS', 'Bahamas', 'Bahamian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BH', 'BHR', 'Bahrain', 'Bahraini');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BD', 'BGD', 'Bangladesh', 'Bangladeshi');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BB', 'BRB', 'Barbados', 'Barbadian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BY', 'BLR', 'Belarus', 'Belarusian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BE', 'BEL', 'Belgium', 'Belgian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BZ', 'BLZ', 'Belize', 'Belizean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BJ', 'BEN', 'Benin', 'Beninese, Beninois');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BM', 'BMU', 'Bermuda', 'Bermudian, Bermudan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BT', 'BTN', 'Bhutan', 'Bhutanese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BO', 'BOL', 'Bolivia (Plurinational State of)', 'Bolivian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnian or Herzegovinian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BW', 'BWA', 'Botswana', 'Motswana, Botswanan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BV', 'BVT', 'Bouvet Island', 'Bouvet Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BR', 'BRA', 'Brazil', 'Brazilian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IO', 'IOT', 'British Indian Ocean Territory', 'BIOT');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BN', 'BRN', 'Brunei Darussalam', 'Bruneian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BG', 'BGR', 'Bulgaria', 'Bulgarian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BF', 'BFA', 'Burkina Faso', 'Burkinabé');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BI', 'BDI', 'Burundi', 'Burundian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CV', 'CPV', 'Cabo Verde', 'Cabo Verdean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KH', 'KHM', 'Cambodia', 'Cambodian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CM', 'CMR', 'Cameroon', 'Cameroonian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CA', 'CAN', 'Canada', 'Canadian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KY', 'CYM', 'Cayman Islands', 'Caymanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CF', 'CAF', 'Central African Republic', 'Central African');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TD', 'TCD', 'Chad', 'Chadian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CL', 'CHL', 'Chile', 'Chilean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CN', 'CHN', 'China', 'Chinese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CX', 'CXR', 'Christmas Island', 'Christmas Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CC', 'CCK', 'Cocos (Keeling) Islands', 'Cocos Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CO', 'COL', 'Colombia', 'Colombian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KM', 'COM', 'Comoros', 'Comoran, Comorian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CG', 'COG', 'Congo (Republic of the)', 'Congolese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CD', 'COD', 'Congo (Democratic Republic of the)', 'Congolese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CK', 'COK', 'Cook Islands', 'Cook Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CR', 'CRI', 'Costa Rica', 'Costa Rican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CI', 'CIV', 'Côte d\'Ivoire', 'Ivorian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('HR', 'HRV', 'Croatia', 'Croatian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CU', 'CUB', 'Cuba', 'Cuban');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CW', 'CUW', 'Curaçao', 'Curaçaoan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CY', 'CYP', 'Cyprus', 'Cypriot');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CZ', 'CZE', 'Czech Republic', 'Czech');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('DK', 'DNK', 'Denmark', 'Danish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('DJ', 'DJI', 'Djibouti', 'Djiboutian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('DM', 'DMA', 'Dominica', 'Dominican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('DO', 'DOM', 'Dominican Republic', 'Dominican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('EC', 'ECU', 'Ecuador', 'Ecuadorian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('EG', 'EGY', 'Egypt', 'Egyptian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SV', 'SLV', 'El Salvador', 'Salvadoran');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GQ', 'GNQ', 'Equatorial Guinea', 'Equatorial Guinean, Equatoguinean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ER', 'ERI', 'Eritrea', 'Eritrean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('EE', 'EST', 'Estonia', 'Estonian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ET', 'ETH', 'Ethiopia', 'Ethiopian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('FK', 'FLK', 'Falkland Islands (Malvinas)', 'Falkland Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('FO', 'FRO', 'Faroe Islands', 'Faroese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('FJ', 'FJI', 'Fiji', 'Fijian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('FI', 'FIN', 'Finland', 'Finnish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('FR', 'FRA', 'France', 'French');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GF', 'GUF', 'French Guiana', 'French Guianese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PF', 'PYF', 'French Polynesia', 'French Polynesian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TF', 'ATF', 'French Southern Territories', 'French Southern Territories');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GA', 'GAB', 'Gabon', 'Gabonese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GM', 'GMB', 'Gambia', 'Gambian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GE', 'GEO', 'Georgia', 'Georgian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('DE', 'DEU', 'Germany', 'German');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GH', 'GHA', 'Ghana', 'Ghanaian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GI', 'GIB', 'Gibraltar', 'Gibraltar');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GR', 'GRC', 'Greece', 'Greek, Hellenic');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GL', 'GRL', 'Greenland', 'Greenlandic');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GD', 'GRD', 'Grenada', 'Grenadian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GP', 'GLP', 'Guadeloupe', 'Guadeloupe');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GU', 'GUM', 'Guam', 'Guamanian, Guambat');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GT', 'GTM', 'Guatemala', 'Guatemalan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GG', 'GGY', 'Guernsey', 'Channel Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GN', 'GIN', 'Guinea', 'Guinean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GW', 'GNB', 'Guinea-Bissau', 'Bissau-Guinean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GY', 'GUY', 'Guyana', 'Guyanese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('HT', 'HTI', 'Haiti', 'Haitian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard Island or McDonald Islands');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('VA', 'VAT', 'Vatican City State', 'Vatican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('HN', 'HND', 'Honduras', 'Honduran');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('HK', 'HKG', 'Hong Kong', 'Hong Kong, Hong Kongese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('HU', 'HUN', 'Hungary', 'Hungarian, Magyar');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IS', 'ISL', 'Iceland', 'Icelandic');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IN', 'IND', 'India', 'Indian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ID', 'IDN', 'Indonesia', 'Indonesian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IR', 'IRN', 'Iran', 'Iranian, Persian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IQ', 'IRQ', 'Iraq', 'Iraqi');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IE', 'IRL', 'Ireland', 'Irish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IM', 'IMN', 'Isle of Man', 'Manx');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IL', 'ISR', 'Israel', 'Israeli');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('IT', 'ITA', 'Italy', 'Italian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('JM', 'JAM', 'Jamaica', 'Jamaican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('JP', 'JPN', 'Japan', 'Japanese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('JE', 'JEY', 'Jersey', 'Channel Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('JO', 'JOR', 'Jordan', 'Jordanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KZ', 'KAZ', 'Kazakhstan', 'Kazakhstani, Kazakh');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KE', 'KEN', 'Kenya', 'Kenyan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KI', 'KIR', 'Kiribati', 'I-Kiribati');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KP', 'PRK', 'Korea (Democratic People\'s Republic of)', 'North Korean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KR', 'KOR', 'Korea (Republic of)', 'South Korean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KW', 'KWT', 'Kuwait', 'Kuwaiti');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LA', 'LAO', 'Lao People\'s Democratic Republic', 'Lao, Laotian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LV', 'LVA', 'Latvia', 'Latvian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LB', 'LBN', 'Lebanon', 'Lebanese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LS', 'LSO', 'Lesotho', 'Basotho');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LR', 'LBR', 'Liberia', 'Liberian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LY', 'LBY', 'Libya', 'Libyan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LI', 'LIE', 'Liechtenstein', 'Liechtenstein');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LT', 'LTU', 'Lithuania', 'Lithuanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LU', 'LUX', 'Luxembourg', 'Luxembourg, Luxembourgish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MO', 'MAC', 'Macao', 'Macanese, Chinese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MK', 'MKD', 'Macedonia (the former Yugoslav Republic of)', 'Macedonian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MG', 'MDG', 'Madagascar', 'Malagasy');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MW', 'MWI', 'Malawi', 'Malawian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MY', 'MYS', 'Malaysia', 'Malaysian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MV', 'MDV', 'Maldives', 'Maldivian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ML', 'MLI', 'Mali', 'Malian, Malinese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MT', 'MLT', 'Malta', 'Maltese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MH', 'MHL', 'Marshall Islands', 'Marshallese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MQ', 'MTQ', 'Martinique', 'Martiniquais, Martinican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MR', 'MRT', 'Mauritania', 'Mauritanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MU', 'MUS', 'Mauritius', 'Mauritian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('YT', 'MYT', 'Mayotte', 'Mahoran');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MX', 'MEX', 'Mexico', 'Mexican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('FM', 'FSM', 'Micronesia (Federated States of)', 'Micronesian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MD', 'MDA', 'Moldova (Republic of)', 'Moldovan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MC', 'MCO', 'Monaco', 'Monégasque, Monacan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MN', 'MNG', 'Mongolia', 'Mongolian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ME', 'MNE', 'Montenegro', 'Montenegrin');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MS', 'MSR', 'Montserrat', 'Montserratian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MA', 'MAR', 'Morocco', 'Moroccan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MZ', 'MOZ', 'Mozambique', 'Mozambican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MM', 'MMR', 'Myanmar', 'Burmese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NA', 'NAM', 'Namibia', 'Namibian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NR', 'NRU', 'Nauru', 'Nauruan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NP', 'NPL', 'Nepal', 'Nepali, Nepalese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NL', 'NLD', 'Netherlands', 'Dutch, Netherlandic');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NC', 'NCL', 'New Caledonia', 'New Caledonian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NZ', 'NZL', 'New Zealand', 'New Zealand, NZ');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NI', 'NIC', 'Nicaragua', 'Nicaraguan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NE', 'NER', 'Niger', 'Nigerien');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NG', 'NGA', 'Nigeria', 'Nigerian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NU', 'NIU', 'Niue', 'Niuean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NF', 'NFK', 'Norfolk Island', 'Norfolk Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MP', 'MNP', 'Northern Mariana Islands', 'Northern Marianan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('NO', 'NOR', 'Norway', 'Norwegian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('OM', 'OMN', 'Oman', 'Omani');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PK', 'PAK', 'Pakistan', 'Pakistani');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PW', 'PLW', 'Palau', 'Palauan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PS', 'PSE', 'Palestine, State of', 'Palestinian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PA', 'PAN', 'Panama', 'Panamanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PG', 'PNG', 'Papua New Guinea', 'Papua New Guinean, Papuan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PY', 'PRY', 'Paraguay', 'Paraguayan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PE', 'PER', 'Peru', 'Peruvian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PH', 'PHL', 'Philippines', 'Philippine, Filipino');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PN', 'PCN', 'Pitcairn', 'Pitcairn Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PL', 'POL', 'Poland', 'Polish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PT', 'PRT', 'Portugal', 'Portuguese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PR', 'PRI', 'Puerto Rico', 'Puerto Rican');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('QA', 'QAT', 'Qatar', 'Qatari');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('RE', 'REU', 'Réunion', 'Réunionese, Réunionnais');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('RO', 'ROU', 'Romania', 'Romanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('RU', 'RUS', 'Russian Federation', 'Russian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('RW', 'RWA', 'Rwanda', 'Rwandan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('BL', 'BLM', 'Saint Barthélemy', 'Barthélemois');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helenian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('KN', 'KNA', 'Saint Kitts and Nevis', 'Kittitian or Nevisian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LC', 'LCA', 'Saint Lucia', 'Saint Lucian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('MF', 'MAF', 'Saint Martin (French part)', 'Saint-Martinoise');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierrais or Miquelonnais');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincentian, Vincentian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('WS', 'WSM', 'Samoa', 'Samoan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SM', 'SMR', 'San Marino', 'Sammarinese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ST', 'STP', 'Sao Tome and Principe', 'São Toméan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SA', 'SAU', 'Saudi Arabia', 'Saudi, Saudi Arabian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SN', 'SEN', 'Senegal', 'Senegalese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('RS', 'SRB', 'Serbia', 'Serbian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SC', 'SYC', 'Seychelles', 'Seychellois');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SL', 'SLE', 'Sierra Leone', 'Sierra Leonean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SG', 'SGP', 'Singapore', 'Singaporean');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SX', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SK', 'SVK', 'Slovakia', 'Slovak');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SI', 'SVN', 'Slovenia', 'Slovenian, Slovene');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SB', 'SLB', 'Solomon Islands', 'Solomon Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SO', 'SOM', 'Somalia', 'Somali, Somalian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ZA', 'ZAF', 'South Africa', 'South African');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia or South Sandwich Islands');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SS', 'SSD', 'South Sudan', 'South Sudanese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ES', 'ESP', 'Spain', 'Spanish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('LK', 'LKA', 'Sri Lanka', 'Sri Lankan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SD', 'SDN', 'Sudan', 'Sudanese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SR', 'SUR', 'Suriname', 'Surinamese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SZ', 'SWZ', 'Swaziland', 'Swazi');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SE', 'SWE', 'Sweden', 'Swedish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('CH', 'CHE', 'Switzerland', 'Swiss');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('SY', 'SYR', 'Syrian Arab Republic', 'Syrian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TW', 'TWN', 'Taiwan, Province of China', 'Chinese, Taiwanese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TJ', 'TJK', 'Tajikistan', 'Tajikistani');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TZ', 'TZA', 'Tanzania, United Republic of', 'Tanzanian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TH', 'THA', 'Thailand', 'Thai');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TL', 'TLS', 'Timor-Leste', 'Timorese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TG', 'TGO', 'Togo', 'Togolese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TK', 'TKL', 'Tokelau', 'Tokelauan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TO', 'TON', 'Tonga', 'Tongan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TT', 'TTO', 'Trinidad and Tobago', 'Trinidadian or Tobagonian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TN', 'TUN', 'Tunisia', 'Tunisian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TR', 'TUR', 'Turkey', 'Turkish');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TM', 'TKM', 'Turkmenistan', 'Turkmen');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('TV', 'TUV', 'Tuvalu', 'Tuvaluan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('UG', 'UGA', 'Uganda', 'Ugandan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('UA', 'UKR', 'Ukraine', 'Ukrainian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('AE', 'ARE', 'United Arab Emirates', 'Emirati, Emirian, Emiri');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('GB', 'GBR', 'United Kingdom of Great Britain and Northern Ireland', 'British, UK');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('UM', 'UMI', 'United States Minor Outlying Islands', 'American');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('US', 'USA', 'United States of America', 'American');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('UY', 'URY', 'Uruguay', 'Uruguayan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('UZ', 'UZB', 'Uzbekistan', 'Uzbekistani, Uzbek');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('VU', 'VUT', 'Vanuatu', 'Ni-Vanuatu, Vanuatuan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('VE', 'VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuelan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('VN', 'VNM', 'Vietnam', 'Vietnamese');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('VG', 'VGB', 'Virgin Islands (British)', 'British Virgin Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('VI', 'VIR', 'Virgin Islands (U.S.)', 'U.S. Virgin Island');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('WF', 'WLF', 'Wallis and Futuna', 'Wallis and Futuna, Wallisian or Futunan');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('EH', 'ESH', 'Western Sahara', 'Sahrawi, Sahrawian, Sahraouian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('YE', 'YEM', 'Yemen', 'Yemeni');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ZM', 'ZMB', 'Zambia', 'Zambian');
INSERT INTO `COUNTRIES` (`country_code`, `iso3`, `name`, `nationality`) VALUES ('ZW', 'ZWE', 'Zimbabwe', 'Zimbabwean');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CUSTOMER`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `CUSTOMER` (`customer_id`, `email`, `password`, `first_name`, `last_name`, `mobile`, `gender`, `joined_date`, `status`, `customer_type`, `address_line_1`, `address_line_2`, `city`, `country`, `region`, `postal_code`, `email_token`, `email_token_expire`, `password_token`, `password_token_expire`) VALUES (0, 'none', NULL, NULL, NULL, NULL, NULL, NULL, 'VERIFIED', 'GUEST', NULL, NULL, NULL, NULL, NULL, NULL, 'none', NULL, 'none', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `AIRLINE`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('4U', 'Germanwings');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('7G', 'Star Flyer');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('9C', 'China SSS');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('A3', 'Aegean Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AA', 'American Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AB', 'Air Berlin');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AC', 'Air Canada');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AF', 'Air France');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AI', 'Air India Limited');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AS', 'Alaska Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AY', 'Finnair');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('AZ', 'Alitalia');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('B6', 'JetBlue Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('BA', 'British Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('BC', 'Skymark Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('BY', 'TUI Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('CA', 'Air China');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('CY', 'Cyprus Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('CZ', 'China Southern Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('DL', 'Delta Air Lines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('EB', 'Wamos Air');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('EL', 'Air Nippon');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('ET', 'Ethiopian Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('FM', 'Shanghai Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('FR', 'Ryanair');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('GF', 'Gulf Air Bahrain');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('HO', 'Juneyao Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('IB', 'Iberia Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('JL', 'Japan Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('KL', 'KLM Royal Dutch Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('KU', 'Kuwait Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('LA', 'LAN Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('LH', 'Lufthansa');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('LS', 'Jet2.com');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('MH', 'Malaysia Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('MT', 'Thomas Cook Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('MU', 'China Eastern Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('NH', 'All Nippon Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('NZ', 'Air New Zealand');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('OA', 'Olympic Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('PK', 'Pakistan International Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('QR', 'Qatar Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('S7', 'S7 Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('SQ', 'Singapore Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('SU', 'Aeroflot Russian Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('TO', 'Transavia France');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('U2', 'easyJet');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('U6', 'Ural Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('UA', 'United Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('UN', 'Transaero Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('US', 'US Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('UX', 'Air Europa');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('VN', 'Vietnam Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('VS', 'Virgin Atlantic Airways');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('VX', 'Virgin America');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('VY', 'Formosa Airlines');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('ZB', 'Air Bourbon');
INSERT INTO `AIRLINE` (`airline_code`, `airline_name`) VALUES ('ZH', 'Shenzhen Airlines');

COMMIT;


-- -----------------------------------------------------
-- Data for table `AIRPLANE`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('319', 'Airbus A319', 134);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('320', 'Airbus A320', 150);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('321', 'Airbus A321', 185);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('330', 'Airbus A330', 293);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('332', 'Airbus A330-200', 225);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('333', 'Airbus A330-300', 283);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('346', 'Airbus A340-600', 342);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('388', 'Airbus A380-800', 525);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('AR8', 'Avro RJ85', 112);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('737', 'Boeing 737', 210);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('733', 'Boeing 737-300', 148);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('735', 'Boeing 737-500', 140);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('738', 'Boeing 737-800', 175);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('744', 'Boeing 747-400', 416);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('757', 'Boeing 757', 240);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('752', 'Boeing 757-200', 228);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('767', 'Boeing 767', 174);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('763', 'Boeing 767-300', 210);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('764', 'Boeing 767-400', 243);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('777', 'Boeing 777', 300);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('772', 'Boeing 777-200', 313);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('773', 'Boeing 777-300', 370);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('77W', 'Boeing 777-300ER', 370);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('787', 'Boeing 787', 267);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('788', 'Boeing 787-8', 325);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('CRK', 'Canadair Regional Jet 1000', 100);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('CR9', 'Canadair Regional Jet 900', 88);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('E90', 'Embraer 190', 95);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('32A', 'Airbus A320 (Sharklet)', 210);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('32B', 'Airbus A321 (Sharklet)', 180);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('32S', 'Airbus (A318/A318/A320/A321)', 222);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('73H', 'Boeing 737-800 (73H)', 160);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('75W', 'Boeing 757-200 (75W)', 230);
INSERT INTO `AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('76W', 'Boeing 767-300ER (76W)', 208);

COMMIT;


-- -----------------------------------------------------
-- Data for table `AIRPORT`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('ATH', 'Eleftherios Venizelos International Airport', 'Athens', 'Greece');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BCN', 'Barcelona International Airport', 'Barcelona', 'Spain');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou', 'China');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DME', 'Domodedovo International Airport', 'Moscow', 'Russia');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('FRA', 'Frankfurt am Main Airport', 'Frankfurt', 'Germany');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('FUK', 'Fukuoka Airport', 'Fukuoka', 'Japan');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('HND', 'Tokyo Haneda International Airport', 'Tokyo', 'Japan');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JFK', 'John F Kennedy International Airport', 'New York', 'United States');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('LCA', 'Larnaca International Airport', 'Larnaca', 'Cyprus');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('LHR', 'London Heathrow Airport', 'London', 'United Kingdom');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('MAD', 'Adolfo Suarez Madrid-Barajas Airport', 'Madrid', 'Spain');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('MAN', 'Manchester Airport', 'Manchester', 'United Kingdom');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('ORY', 'Paris-Orly Airport', 'Paris', 'France');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PFO', 'Paphos International Airport', 'Paphos', 'Cyprus');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SFO', 'San Francisco International Airport', 'San Francisco', 'United States');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SHA', 'Shanghai Hongqiao International Airport', 'Shanghai', 'China');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SKG', 'Thessaloniki Macedonia International Airport', 'Thessaloniki', 'Greece');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('STR', 'Stuttgart Airport', 'Stuttgart', 'Germany');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SVO', 'Sheremetyevo International Airport', 'Moscow', 'Russia');
INSERT INTO `AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TLS', 'Toulouse-Blagnac Airport', 'Toulouse', 'France');

COMMIT;


-- -----------------------------------------------------
-- Data for table `INSURANCE`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `INSURANCE` (`insurance_id`, `medical_bills`, `trip_cancellation`, `lost_baggage`, `travel_insurance`, `liability`, `price`) VALUES ('none', 0, 0, 0, 0, 0, 0);
INSERT INTO `INSURANCE` (`insurance_id`, `medical_bills`, `trip_cancellation`, `lost_baggage`, `travel_insurance`, `liability`, `price`) VALUES ('basic', 1, 1, 0, 0, 0, 15);
INSERT INTO `INSURANCE` (`insurance_id`, `medical_bills`, `trip_cancellation`, `lost_baggage`, `travel_insurance`, `liability`, `price`) VALUES ('plus', 1, 1, 1, 1, 1, 25);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BAGGAGE`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `BAGGAGE` (`bag_id`, `weight`, `price`) VALUES ('cabin', 0, 7);
INSERT INTO `BAGGAGE` (`bag_id`, `weight`, `price`) VALUES ('small', 25, 23);
INSERT INTO `BAGGAGE` (`bag_id`, `weight`, `price`) VALUES ('large', 50, 32);

COMMIT;

