-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 01:04:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FlightFinder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `FlightFinder`.`NATIONALITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`NATIONALITIES` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`NATIONALITIES` (
  `nationality_code` VARCHAR(2) NOT NULL,
  `nationality_full_name` VARCHAR(50) NULL,
  PRIMARY KEY (`nationality_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightFinder`.`PASSENGER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`PASSENGER` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`PASSENGER` (
  `passenger_id` VARCHAR(10) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `date_of_birth` DATE NULL,
  `gender` VARCHAR(6) NULL,
  `id_type` VARCHAR(10) NULL,
  `id_expiration_date` DATE NULL,
  `nationality` VARCHAR(2) NULL,
  PRIMARY KEY (`passenger_id`),
  CONSTRAINT `fk_PASSENGER_NATIONALITIES`
    FOREIGN KEY (`nationality`)
    REFERENCES `FlightFinder`.`NATIONALITIES` (`nationality_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PASSENGER_NATIONALITIES_idx` ON `FlightFinder`.`PASSENGER` (`nationality` ASC);


-- -----------------------------------------------------
-- Table `FlightFinder`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`CUSTOMER` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(500) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `mobile` VARCHAR(10) NULL,
  `gender` VARCHAR(6) NULL,
  `joined_date` DATE NULL,
  `status` VARCHAR(50) NULL,
  `customer_type` VARCHAR(10) NULL,
  `email_token` VARCHAR(100) NULL,
  `email_token_expire` DATETIME NULL,
  `password_token` VARCHAR(100) NULL,
  `password_token_expire` DATETIME NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `FlightFinder`.`CUSTOMER` (`email` ASC);

CREATE UNIQUE INDEX `email_token_UNIQUE` ON `FlightFinder`.`CUSTOMER` (`email_token` ASC);

CREATE UNIQUE INDEX `password_token_UNIQUE` ON `FlightFinder`.`CUSTOMER` (`password_token` ASC);


-- -----------------------------------------------------
-- Table `FlightFinder`.`AIRLINE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`AIRLINE` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`AIRLINE` (
  `airline_code` VARCHAR(2) NOT NULL,
  `airline_name` VARCHAR(50) NULL,
  PRIMARY KEY (`airline_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightFinder`.`AIRPLANE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`AIRPLANE` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`AIRPLANE` (
  `airplane_model` VARCHAR(3) NOT NULL,
  `airplane_name` VARCHAR(100) NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`airplane_model`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightFinder`.`AIRPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`AIRPORT` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`AIRPORT` (
  `airport_code` VARCHAR(3) NOT NULL,
  `airport_name` VARCHAR(50) NULL,
  `city` VARCHAR(50) NULL,
  `country` VARCHAR(50) NULL,
  PRIMARY KEY (`airport_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightFinder`.`FLIGHT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`FLIGHT` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`FLIGHT` (
  `flight_id` VARCHAR(10) NOT NULL,
  `airline` VARCHAR(2) NOT NULL,
  `airplane` VARCHAR(3) NOT NULL,
  `from_airport` VARCHAR(3) NOT NULL,
  `to_airport` VARCHAR(3) NOT NULL,
  `dep_date` DATE NOT NULL,
  `dep_time` TIME NULL,
  `arr_date` DATE NULL,
  `arr_time` TIME NULL,
  `duration` TIME NULL,
  `class` VARCHAR(50) NOT NULL,
  `price` INT NULL,
  `change_fee` INT NULL,
  `cancel_fee` INT NULL,
  `taxes` INT NULL,
  `discount` DECIMAL(5) NULL,
  `occupied_capacity` INT NULL,
  `status` VARCHAR(50) NULL,
  PRIMARY KEY (`flight_id`, `dep_date`, `class`),
  CONSTRAINT `fk_FLIGHT_AIRLINE1`
    FOREIGN KEY (`airline`)
    REFERENCES `FlightFinder`.`AIRLINE` (`airline_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FLIGHT_AIRPLANE1`
    FOREIGN KEY (`airplane`)
    REFERENCES `FlightFinder`.`AIRPLANE` (`airplane_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FLIGHT_AIRPORT1`
    FOREIGN KEY (`from_airport`)
    REFERENCES `FlightFinder`.`AIRPORT` (`airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FLIGHT_AIRPORT2`
    FOREIGN KEY (`to_airport`)
    REFERENCES `FlightFinder`.`AIRPORT` (`airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FLIGHT_AIRLINE1_idx` ON `FlightFinder`.`FLIGHT` (`airline` ASC);

CREATE INDEX `fk_FLIGHT_AIRPLANE1_idx` ON `FlightFinder`.`FLIGHT` (`airplane` ASC);

CREATE INDEX `fk_FLIGHT_AIRPORT1_idx` ON `FlightFinder`.`FLIGHT` (`from_airport` ASC);

CREATE INDEX `fk_FLIGHT_AIRPORT2_idx` ON `FlightFinder`.`FLIGHT` (`to_airport` ASC);


-- -----------------------------------------------------
-- Table `FlightFinder`.`BOOKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`BOOKING` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`BOOKING` (
  `booking_id` VARCHAR(6) NOT NULL,
  `customer_id` INT NOT NULL,
  `depart_flight_id` VARCHAR(10) NOT NULL,
  `return_flight_id` VARCHAR(10) NULL,
  `depart_flight_date` DATE NOT NULL,
  `return_flight_date` DATE NULL,
  `flight_class` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `mobile` VARCHAR(10) NULL,
  `booking_date` DATE NULL,
  `last_modify_date` DATE NULL,
  `total_passengers` INT NULL,
  `total_baggage` INT NULL,
  `baggage_per_passenger` INT NULL,
  `price_per_passenger` INT NULL,
  `total_price` INT NULL,
  `payment_type` VARCHAR(15) NULL,
  `flight_type` VARCHAR(50) NULL,
  `status` VARCHAR(50) NULL,
  PRIMARY KEY (`booking_id`, `customer_id`, `depart_flight_id`, `depart_flight_date`, `flight_class`),
  CONSTRAINT `fk_BOOKING_CUSTOMER1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `FlightFinder`.`CUSTOMER` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_BOOKING_FLIGHT1`
    FOREIGN KEY (`depart_flight_id` , `depart_flight_date` , `flight_class`)
    REFERENCES `FlightFinder`.`FLIGHT` (`flight_id` , `dep_date` , `class`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_BOOKING_CUSTOMER1_idx` ON `FlightFinder`.`BOOKING` (`customer_id` ASC);

CREATE INDEX `fk_BOOKING_FLIGHT1_idx` ON `FlightFinder`.`BOOKING` (`depart_flight_id` ASC, `depart_flight_date` ASC, `flight_class` ASC);


-- -----------------------------------------------------
-- Table `FlightFinder`.`INSURANCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`INSURANCE` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`INSURANCE` (
  `insurance_id` VARCHAR(6) NOT NULL,
  `medical_bills` TINYINT NULL,
  `trip_cancellation` TINYINT NULL,
  `lost_baggage` TINYINT NULL,
  `travel_insurance` TINYINT NULL,
  `liability` TINYINT NULL,
  `price` INT NULL,
  PRIMARY KEY (`insurance_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightFinder`.`BAGGAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`BAGGAGE` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`BAGGAGE` (
  `bag_id` VARCHAR(6) NOT NULL,
  `weight` INT NULL,
  `price` INT NULL,
  PRIMARY KEY (`bag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlightFinder`.`HAS_BOOKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FlightFinder`.`HAS_BOOKING` ;

CREATE TABLE IF NOT EXISTS `FlightFinder`.`HAS_BOOKING` (
  `booking_id` VARCHAR(6) NOT NULL,
  `passenger_id` VARCHAR(10) NOT NULL,
  `insurance` VARCHAR(6) NULL,
  `chkd_cabin_bag_dep` VARCHAR(6) NULL DEFAULT 'cabin',
  `chkd_cabin_bag_dep_amount` INT NULL DEFAULT 1,
  `chkd_small_bag__dep` VARCHAR(6) NULL DEFAULT 'small',
  `chkd_small_bag_dep_amount` INT NULL DEFAULT 0,
  `chkd_large_bag_dep` VARCHAR(6) NULL DEFAULT 'large',
  `chkd_large_bag_dep_amount` INT NULL DEFAULT 0,
  `chkd_cabin_bag_ret` VARCHAR(6) NULL DEFAULT 'cabin',
  `chkd_cabin_bag_ret_amount` INT NULL DEFAULT 0,
  `chkd_small_bag_ret` VARCHAR(6) NULL DEFAULT 'small',
  `chkd_small_bag_ret_amount` INT NULL DEFAULT 0,
  `chkd_large_bag_ret` VARCHAR(6) NULL DEFAULT 'large',
  `chkd_large_bag_ret_amount` INT NULL DEFAULT 0,
  PRIMARY KEY (`booking_id`, `passenger_id`),
  CONSTRAINT `fk_HAS_BOOKING_PASSENGER`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `FlightFinder`.`PASSENGER` (`passenger_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HAS_BOOKING_BOOKING`
    FOREIGN KEY (`booking_id`)
    REFERENCES `FlightFinder`.`BOOKING` (`booking_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_INSURANCE`
    FOREIGN KEY (`insurance`)
    REFERENCES `FlightFinder`.`INSURANCE` (`insurance_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE1`
    FOREIGN KEY (`chkd_cabin_bag_dep`)
    REFERENCES `FlightFinder`.`BAGGAGE` (`bag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE2`
    FOREIGN KEY (`chkd_small_bag__dep`)
    REFERENCES `FlightFinder`.`BAGGAGE` (`bag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE3`
    FOREIGN KEY (`chkd_large_bag_dep`)
    REFERENCES `FlightFinder`.`BAGGAGE` (`bag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE4`
    FOREIGN KEY (`chkd_cabin_bag_ret`)
    REFERENCES `FlightFinder`.`BAGGAGE` (`bag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE5`
    FOREIGN KEY (`chkd_small_bag_ret`)
    REFERENCES `FlightFinder`.`BAGGAGE` (`bag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HAS_BOOKING_BAGGAGE6`
    FOREIGN KEY (`chkd_large_bag_ret`)
    REFERENCES `FlightFinder`.`BAGGAGE` (`bag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_HAS_BOOKING_BOOKING1_idx` ON `FlightFinder`.`HAS_BOOKING` (`booking_id` ASC);

CREATE INDEX `fk_HAS_BOOKING_INSURANCE1_idx` ON `FlightFinder`.`HAS_BOOKING` (`insurance` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE1_idx` ON `FlightFinder`.`HAS_BOOKING` (`chkd_cabin_bag_dep` ASC);

CREATE INDEX `fk_HAS_BOOKING_PASSENGER1_idx` ON `FlightFinder`.`HAS_BOOKING` (`passenger_id` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE2_idx` ON `FlightFinder`.`HAS_BOOKING` (`chkd_small_bag__dep` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE3_idx` ON `FlightFinder`.`HAS_BOOKING` (`chkd_large_bag_dep` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE4_idx` ON `FlightFinder`.`HAS_BOOKING` (`chkd_cabin_bag_ret` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE5_idx` ON `FlightFinder`.`HAS_BOOKING` (`chkd_small_bag_ret` ASC);

CREATE INDEX `fk_HAS_BOOKING_BAGGAGE6_idx` ON `FlightFinder`.`HAS_BOOKING` (`chkd_large_bag_ret` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `FlightFinder`.`NATIONALITIES`
-- -----------------------------------------------------
START TRANSACTION;
USE `FlightFinder`;
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AX', 'Åland Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AL', 'Albania');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('DZ', 'Algeria');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AS', 'American Samoa');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AD', 'Andorra');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AO', 'Angola');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AI', 'Anguilla');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AQ', 'Antarctica');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AR', 'Argentina');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AM', 'Armenia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AW', 'Aruba');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AU', 'Australia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AT', 'Austria');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AZ', 'Azerbaijan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BS', 'Bahamas');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BH', 'Bahrain');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BB', 'Barbados');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BY', 'Belarus');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BE', 'Belgium');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BZ', 'Belize');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BJ', 'Benin');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BM', 'Bermuda');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BT', 'Bhutan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BO', 'Bolivia, Plurinational State of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BW', 'Botswana');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BV', 'Bouvet Island');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BR', 'Brazil');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BI', 'Burundi');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KH', 'Cambodia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CM', 'Cameroon');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CA', 'Canada');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CV', 'Cape Verde');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KY', 'Cayman Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CF', 'Central African Republic');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TD', 'Chad');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CL', 'Chile');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CN', 'China');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CX', 'Christmas Island');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CO', 'Colombia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KM', 'Comoros');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CG', 'Congo');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CD', 'Congo, the Democratic Republic of the');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CK', 'Cook Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CI', 'Côte d\'Ivoire');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('HR', 'Croatia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CU', 'Cuba');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CW', 'Curaçao');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CY', 'Cyprus');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CZ', 'Czech Republic');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('DK', 'Denmark');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('DM', 'Dominica');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('DO', 'Dominican Republic');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('EC', 'Ecuador');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('EG', 'Egypt');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SV', 'El Salvador');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ER', 'Eritrea');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('EE', 'Estonia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ET', 'Ethiopia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('FO', 'Faroe Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('FJ', 'Fiji');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('FI', 'Finland');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('FR', 'France');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GF', 'French Guiana');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PF', 'French Polynesia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TF', 'French Southern Territories');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GA', 'Gabon');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GM', 'Gambia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GE', 'Georgia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('DE', 'Germany');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GH', 'Ghana');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GR', 'Greece');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GL', 'Greenland');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GD', 'Grenada');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GU', 'Guam');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GT', 'Guatemala');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GG', 'Guernsey');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GN', 'Guinea');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GY', 'Guyana');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('HT', 'Haiti');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('VA', 'Holy See (Vatican City State)');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('HN', 'Honduras');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('HK', 'Hong Kong');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('HU', 'Hungary');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IS', 'Iceland');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IN', 'India');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ID', 'Indonesia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IR', 'Iran, Islamic Republic of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IQ', 'Iraq');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IE', 'Ireland');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IM', 'Isle of Man');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IL', 'Israel');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('IT', 'Italy');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('JM', 'Jamaica');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('JP', 'Japan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('JE', 'Jersey');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('JO', 'Jordan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KZ', 'Kazakhstan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KE', 'Kenya');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KI', 'Kiribati');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KP', 'Korea, Democratic People\'s Republic of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KR', 'Korea, Republic of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KW', 'Kuwait');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LA', 'Lao People\'s Democratic Republic');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LV', 'Latvia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LB', 'Lebanon');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LS', 'Lesotho');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LR', 'Liberia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LY', 'Libya');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LT', 'Lithuania');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LU', 'Luxembourg');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MO', 'Macao');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MK', 'Macedonia, the former Yugoslav Republic of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MG', 'Madagascar');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MW', 'Malawi');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MY', 'Malaysia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MV', 'Maldives');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ML', 'Mali');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MT', 'Malta');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MH', 'Marshall Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MQ', 'Martinique');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MR', 'Mauritania');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MU', 'Mauritius');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('YT', 'Mayotte');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MX', 'Mexico');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MC', 'Monaco');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MN', 'Mongolia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ME', 'Montenegro');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MS', 'Montserrat');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MA', 'Morocco');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MZ', 'Mozambique');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MM', 'Myanmar');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NA', 'Namibia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NR', 'Nauru');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NP', 'Nepal');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NL', 'Netherlands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NC', 'New Caledonia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NZ', 'New Zealand');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NE', 'Niger');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NG', 'Nigeria');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NU', 'Niue');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NF', 'Norfolk Island');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('NO', 'Norway');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('OM', 'Oman');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PK', 'Pakistan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PW', 'Palau');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PS', 'Palestinian Territory, Occupied');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PA', 'Panama');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PG', 'Papua New Guinea');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PY', 'Paraguay');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PE', 'Peru');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PH', 'Philippines');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PL', 'Poland');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PT', 'Portugal');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('QA', 'Qatar');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('RE', 'Réunion');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('RO', 'Romania');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('RU', 'Russian Federation');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('RW', 'Rwanda');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('MF', 'Saint Martin (French part)');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('WS', 'Samoa');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SM', 'San Marino');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SA', 'Saudi Arabia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SN', 'Senegal');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('RS', 'Serbia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SC', 'Seychelles');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SG', 'Singapore');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SX', 'Sint Maarten (Dutch part)');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SK', 'Slovakia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SI', 'Slovenia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SB', 'Solomon Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SO', 'Somalia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ZA', 'South Africa');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SS', 'South Sudan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('ES', 'Spain');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SD', 'Sudan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SR', 'Suriname');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SZ', 'Swaziland');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SE', 'Sweden');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('CH', 'Switzerland');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TW', 'Taiwan, Province of China');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TJ', 'Tajikistan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TH', 'Thailand');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TL', 'Timor-Leste');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TG', 'Togo');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TK', 'Tokelau');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TO', 'Tonga');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TN', 'Tunisia');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TR', 'Turkey');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('UG', 'Uganda');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('UA', 'Ukraine');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('AE', 'United Arab Emirates');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('GB', 'United Kingdom');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('US', 'United States');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('UY', 'Uruguay');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('VE', 'Venezuela, Bolivarian Republic of');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('VN', 'Viet Nam');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('VG', 'Virgin Islands, British');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('VI', 'Virgin Islands, U.S.');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('WF', 'Wallis and Futuna');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('EH', 'Western Sahara');
INSERT INTO `FlightFinder`.`NATIONALITIES` (`nationality_code`, `nationality_full_name`) VALUES ('YE', 'Yemen');

COMMIT;


-- -----------------------------------------------------
-- Data for table `FlightFinder`.`CUSTOMER`
-- -----------------------------------------------------
START TRANSACTION;
USE `FlightFinder`;
INSERT INTO `FlightFinder`.`CUSTOMER` (`customer_id`, `email`, `password`, `first_name`, `last_name`, `mobile`, `gender`, `joined_date`, `status`, `customer_type`, `email_token`, `email_token_expire`, `password_token`, `password_token_expire`) VALUES (0, 'none', NULL, NULL, NULL, NULL, NULL, NULL, 'CONFIRMED', 'GUEST', 'none', NULL, 'none', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `FlightFinder`.`AIRLINE`
-- -----------------------------------------------------
START TRANSACTION;
USE `FlightFinder`;
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('4U', 'Germanwings');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('7G', 'Star Flyer');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('9C', 'China SSS');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('A3', 'Aegean Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AA', 'American Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AB', 'Air Berlin');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AC', 'Air Canada');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AF', 'Air France');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AI', 'Air India Limited');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AS', 'Alaska Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AY', 'Finnair');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('AZ', 'Alitalia');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('B6', 'JetBlue Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('BA', 'British Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('BC', 'Skymark Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('BY', 'TUI Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('CA', 'Air China');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('CY', 'Cyprus Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('CZ', 'China Southern Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('DL', 'Delta Air Lines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('EB', 'Wamos Air');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('EL', 'Air Nippon');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('ET', 'Ethiopian Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('FM', 'Shanghai Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('FR', 'Ryanair');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('GF', 'Gulf Air Bahrain');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('HO', 'Juneyao Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('IB', 'Iberia Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('JL', 'Japan Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('KL', 'KLM Royal Dutch Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('KU', 'Kuwait Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('LA', 'LAN Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('LH', 'Lufthansa');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('LS', 'Jet2.com');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('MH', 'Malaysia Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('MT', 'Thomas Cook Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('MU', 'China Eastern Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('NH', 'All Nippon Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('NZ', 'Air New Zealand');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('OA', 'Olympic Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('PK', 'Pakistan International Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('QR', 'Qatar Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('S7', 'S7 Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('SQ', 'Singapore Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('SU', 'Aeroflot Russian Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('TO', 'Transavia France');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('U2', 'easyJet');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('U6', 'Ural Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('UA', 'United Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('UN', 'Transaero Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('US', 'US Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('UX', 'Air Europa');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('VN', 'Vietnam Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('VS', 'Virgin Atlantic Airways');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('VX', 'Virgin America');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('VY', 'Formosa Airlines');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('ZB', 'Air Bourbon');
INSERT INTO `FlightFinder`.`AIRLINE` (`airline_code`, `airline_name`) VALUES ('ZH', 'Shenzhen Airlines');

COMMIT;


-- -----------------------------------------------------
-- Data for table `FlightFinder`.`AIRPLANE`
-- -----------------------------------------------------
START TRANSACTION;
USE `FlightFinder`;
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('319', 'Airbus A319', 134);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('320', 'Airbus A320', 150);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('321', 'Airbus A321', 185);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('330', 'Airbus A330', 293);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('332', 'Airbus A330-200', 225);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('333', 'Airbus A330-300', 283);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('346', 'Airbus A340-600', 342);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('388', 'Airbus A380-800', 525);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('AR8', 'Avro RJ85', 112);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('737', 'Boeing 737', 210);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('733', 'Boeing 737-300', 148);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('735', 'Boeing 737-500', 140);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('738', 'Boeing 737-800', 175);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('744', 'Boeing 747-400', 416);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('757', 'Boeing 757', 240);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('752', 'Boeing 757-200', 228);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('767', 'Boeing 767', 174);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('763', 'Boeing 767-300', 210);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('764', 'Boeing 767-400', 243);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('777', 'Boeing 777', 300);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('772', 'Boeing 777-200', 313);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('773', 'Boeing 777-300', 370);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('77W', 'Boeing 777-300ER', 370);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('787', 'Boeing 787', 267);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('788', 'Boeing 787-8', 325);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('CRK', 'Canadair Regional Jet 1000', 100);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('CR9', 'Canadair Regional Jet 900', 88);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('E90', 'Embraer 190', 95);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('32A', 'Airbus A320 (Sharklet)', 210);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('32B', 'Airbus A321 (Sharklet)', 180);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('32S', 'Airbus (A318/A318/A320/A321)', 222);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('73H', 'Boeing 737-800 (73H)', 160);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('75W', 'Boeing 757-200 (75W)', 230);
INSERT INTO `FlightFinder`.`AIRPLANE` (`airplane_model`, `airplane_name`, `capacity`) VALUES ('76W', 'Boeing 767-300ER (76W)', 208);

COMMIT;


-- -----------------------------------------------------
-- Data for table `FlightFinder`.`AIRPORT`
-- -----------------------------------------------------
START TRANSACTION;
USE `FlightFinder`;
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('ATH', 'Eleftherios Venizelos International Airport', 'Athens', 'Greece');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BCN', 'Barcelona International Airport', 'Barcelona', 'Spain');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou', 'China');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DME', 'Domodedovo International Airport', 'Moscow', 'Russia');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('FRA', 'Frankfurt am Main Airport', 'Frankfurt', 'Germany');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('FUK', 'Fukuoka Airport', 'Fukuoka', 'Japan');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('HND', 'Tokyo Haneda International Airport', 'Tokyo', 'Japan');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JFK', 'John F Kennedy International Airport', 'New York', 'United States');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('LCA', 'Larnaca International Airport', 'Larnaca', 'Cyprus');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('LHR', 'London Heathrow Airport', 'London', 'United Kingdom');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('MAD', 'Adolfo Suarez Madrid-Barajas Airport', 'Madrid', 'Spain');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('MAN', 'Manchester Airport', 'Manchester', 'United Kingdom');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('ORY', 'Paris-Orly Airport', 'Paris', 'France');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PFO', 'Paphos International Airport', 'Paphos', 'Cyprus');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SFO', 'San Francisco International Airport', 'San Francisco', 'United States');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SHA', 'Shanghai Hongqiao International Airport', 'Shanghai', 'China');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SKG', 'Thessaloniki Macedonia International Airport', 'Thessaloniki', 'Greece');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('STR', 'Stuttgart Airport', 'Stuttgart', 'Germany');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SVO', 'Sheremetyevo International Airport', 'Moscow', 'Russia');
INSERT INTO `FlightFinder`.`AIRPORT` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TLS', 'Toulouse-Blagnac Airport', 'Toulouse', 'France');

COMMIT;


-- -----------------------------------------------------
-- Data for table `FlightFinder`.`INSURANCE`
-- -----------------------------------------------------
START TRANSACTION;
USE `FlightFinder`;
INSERT INTO `FlightFinder`.`INSURANCE` (`insurance_id`, `medical_bills`, `trip_cancellation`, `lost_baggage`, `travel_insurance`, `liability`, `price`) VALUES ('none', 0, 0, 0, 0, 0, 0);
INSERT INTO `FlightFinder`.`INSURANCE` (`insurance_id`, `medical_bills`, `trip_cancellation`, `lost_baggage`, `travel_insurance`, `liability`, `price`) VALUES ('basic', 1, 1, 0, 0, 0, 15);
INSERT INTO `FlightFinder`.`INSURANCE` (`insurance_id`, `medical_bills`, `trip_cancellation`, `lost_baggage`, `travel_insurance`, `liability`, `price`) VALUES ('plus', 1, 1, 1, 1, 1, 25);

COMMIT;


-- -----------------------------------------------------
-- Data for table `FlightFinder`.`BAGGAGE`
-- -----------------------------------------------------
START TRANSACTION;
USE `FlightFinder`;
INSERT INTO `FlightFinder`.`BAGGAGE` (`bag_id`, `weight`, `price`) VALUES ('cabin', 0, 7);
INSERT INTO `FlightFinder`.`BAGGAGE` (`bag_id`, `weight`, `price`) VALUES ('small', 25, 23);
INSERT INTO `FlightFinder`.`BAGGAGE` (`bag_id`, `weight`, `price`) VALUES ('large', 50, 32);

COMMIT;

