version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.487.0
    - 1.489.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.533.0
    - 1.538.0
    - 1.542.0
    - 1.558.0
    - 1.563.0
    - 1.564.0
    - 1.566.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
  - dependency-name: mongodb
    versions:
    - 3.6.3
    - 3.6.5
  - dependency-name: winston-daily-rotate-file
    versions:
    - 4.5.1
  - dependency-name: connect-mongo
    versions:
    - 4.3.0
    - 4.3.1
    - 4.4.0
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: debug
    versions:
    - 4.3.1
  - dependency-name: pug
    versions:
    - 3.0.1
  - dependency-name: pug-code-gen
    versions:
    - 3.0.2
  - dependency-name: systeminformation
    versions:
    - 4.34.11
    - 4.34.13
    - 4.34.14
    - 4.34.15
    - 4.34.9
  - dependency-name: "@prettier/plugin-pug"
    versions:
    - 1.13.2
    - 1.13.3
    - 1.13.4
  - dependency-name: express-rate-limit
    versions:
    - 5.2.3
    - 5.2.5
